image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  # xdebug port
  - port: 9000
    onOpen: ignore

# Commenting out. We'll run these manually in class.
tasks:
  - init: composer install && alias drush=/workspace/drupal/vendor/drush/drush/drush && drush si demo_umami -y

vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2
