image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  # xdebug port
  - port: 9000
    onOpen: ignore

# Commenting out. We'll run these manually in class.
tasks:
  - init: |
      composer install
      mysql -u root -e "create database db"

vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2
