image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  # xdebug port
  - port: 9000
    onOpen: ignore

# Commenting out. We'll run these manually in class.
tasks:
  - init: gp await-port 3306 && mysql -uroot -e "CREATE USER 'db'@'localhost' IDENTIFIED BY 'db';" && mysql -uroot -e "CREATE DATABASE db" && mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'db'@'localhost';" && composer install && alias drush=/workspace/drupal/vendor/drush/drush/drush && /workspace/drupal/vendor/drush/drush/drush sqlc < /workspace/drupal/umami_db.sql && php -S 0.0.0.0:8000 -t web/
  - command: echo "When Drupal window opens & loads, you can use this command line window.\n" && alias drush=/workspace/drupal/vendor/drush/drush/drush

vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2
